export enum EventType {
    CARD_ADDED = 'CARD_ADDED',
    CARD_ACTIVATED = 'CARD_ACTIVATED',
    CARD_DISABLED = 'CARD_DISABLED',
    CARD_LIMIT_CHANGED = 'CARD_LIMIT_CHANGED',
    CARD_RESET_PIN_INITIATED = 'CARD_RESET_PIN_INITIATED',
    CARD_3DSECURE_ACTIVATED = 'CARD_3DSECURE_ACTIVATED',
    CARD_3DSECURE_DISABLED = 'CARD_3DSECURE_DISABLED',
    RELOAD_PREPAID_CARD = 'RELOAD_PREPAID_CARD',
    RELOAD_PREPAID_CARD_FAILED = 'RELOAD_PREPAID_CARD_FAILED',
}

